name: CI NestJS

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: beckendsbo

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: beckendsbo/package-lock.json

      - name: Install dependencies
        working-directory: beckendsbo
        run: npm ci

      - name: Build aplikasi
        working-directory: beckendsbo
        run: npm run build

      - name: Jalankan unit test
        working-directory: beckendsbo
        run: npm test

        