name: CI NestJS

on:
  push:
<<<<<<< HEAD
    branches: 
    - develop
    - main
  pull_request:
    branches: 
    - develop
    - main
=======
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main
>>>>>>> 169abdd814f4a1c7e2e0ec4accc26bef520d5a68

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: beckendsbo

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
<<<<<<< HEAD
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: beckendsbo/package-lock.json
=======
          node-version: 22
>>>>>>> 169abdd814f4a1c7e2e0ec4accc26bef520d5a68

      - name: Install dependencies
        run: npm ci

      - name: Build aplikasi
        run: npm run build

      - name: Jalankan unit test
        run: npm test